version: '3.8'

services:
  web:
    image: alymjanrejepov/voting-app:latest
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/votingApp
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  mongodata:
